
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64" #Sistema operacional
  config.vm.hostname = "control-node" #Nome da VM
  config.vm.network "private_network", ip: "192.168.56.2" #Configuração de rede

end
