
Vagrant.configure("2") do |config|
  
  config.vm.hostname = "db01" #nome da VM
  config.vm.box = "ubuntu/jammy64" #Sistema operacional
  config.vm.network "private_network", ip: "192.168.56.4" #Configuração de rede
  config.vm.network "forwarded_port", guest: 3306, host: 3306 #Redirecionamento de Porta 
  config.vm.provision "shell", path:"provision.sh" #Configurando o arquivo de provisionamento 
  
end
